name: cpacs-cfd
channels:
  - dlr-sc
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - attr=2.5.2
  - blosc=1.21.6
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cftime=1.6.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - fltk=1.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freeglut=3.2.2
  - freeimage=3.18.0
  - freeimageplus=3.18.0
  - freetype=2.14.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.86.1
  - glib-tools=2.86.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h5py=3.15.1
  - harfbuzz=11.5.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - icu=75.1
  - imath=3.2.1
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - jasper=4.2.8
  - jxrlib=1.1
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.76
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcups=2.3.3
  - libcurl=8.17.0
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libfabric=2.3.1
  - libfabric1=2.3.1
  - libffi=3.5.2
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.1
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpmix=5.0.8
  - libpng=1.6.50
  - libpq=17.6
  - libraw=0.21.4
  - libsndfile=1.2.2
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.2
  - libtiff=4.7.1
  - libudev1=258.2
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mdurl=0.1.2
  - meshio=5.3.5
  - mpg123=1.32.9
  - mpi=1.0.1
  - mpi4py=4.1.1
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf4=1.7.3
  - nspr=4.38
  - nss=3.117
  - numpy=2.3.4
  - occt=7.8.1
  - opencascade=7.6.2
  - openexr=3.3.5
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openmpi=5.0.8
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pythonocc-core=7.6.2
  - pytz=2025.2
  - qhull=2020.2
  - qt=5.15.15
  - qt-main=5.15.15
  - qt-webengine=5.15.15
  - rapidjson=1.1.0.post20240409
  - rdma-core=60.0
  - readline=8.2
  - rich=14.2.0
  - scipy=1.16.3
  - setuptools=80.9.0
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.2
  - su2=8.3.0
  - tbb=2019.5
  - tigl3=3.5.0rc1
  - tixi3=3.3.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - tornado=6.5.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucc=1.5.1
  - ucx=1.19.0
  - unicodedata2=17.0.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxmu=1.2.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - aiofiles==24.1.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - brotli==1.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - fastapi==0.121.1
      - ffmpy==0.6.4
      - filelock==3.20.0
      - fsspec==2025.10.0
      - gmsh==4.15.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.2
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - orjson==3.11.4
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - python-multipart==0.0.20
      - pyvista==0.46.4
      - pyyaml==6.0.3
      - requests==2.32.5
      - ruff==0.14.4
      - safehttpx==0.1.7
      - scooby==0.11.0
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - starlette==0.49.3
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - vtk==9.5.2
      - websockets==15.0.1
prefix: /home/sebastian/miniconda3/envs/cpacs-cfd
